### ISSUE TITLE
pkgdown action not updating website

### ISSUE THREAD

**Issue by dieghernan** [eliocamp/metR#191]
Hi @eliocamp 

While improving the documentation of **tidyterra** and how it can be combined with **metR** ([link](https://dieghernan.github.io/tidyterra/dev/articles/faqs.html#tidyterra-and-metr)) I noticed that the website is outdated (currently  showing docs for `0.14.1,` CRAN release is `0.15.0`.

I think since 55c4050c76eff7497c15596ac6e2ae3fd3493f68 the pkgdown action just pushes the infraestructure built with **miniCRAN**, but not the site created with **pkgdown** immediately before.

I saw that you use the r-universe (https://eliocamp.r-universe.dev/), so I am just wondering if it is necessary also to create a CRAN-like repo with this action since it's redundant, in fact both CRAN-like repos should be hosting the package built with the most up-to-date commit.

In any case I just wanted to bring your attention on this, since I really enjoy this package and outdated documentation can be misleading.

Best

**Comment by eliocamp** [comment]
> I am just wondering if it is necessary also to create a CRAN-like repo with this action

No, it's not. And I was meaning to revert this. I did this mostly to test if it could be done (which is my motivation for a lot of my projects) but then I realised that it has some serious drawbacks. A big one is that if the package is installed from this repo, then it cannot be restored with renv, since it always only has the latest version. 

Thanks for pointing out the issue, I'll fix it asap.
