### ISSUE TITLE
plot question

### ISSUE THREAD

**Issue by fipoucat** [eliocamp/metR#192]
Hello Elio,
I would like to plot this below kind of grid structure and want to use your package metR.

```
$grid_clas
# A tibble: 3,536 × 10
       x     y time       var   units    WT  xdim  ydim mean_WT_value
   <dbl> <dbl> <date>     <chr> <chr> <dbl> <int> <int>         <dbl>
 1 -10      60 2000-01-01 z500  m         1     1     1         5572.
 2  -7.5    60 2000-01-01 z500  m         1     1     1         5583.
 3  -5      60 2000-01-01 z500  m         1     1     1         5590.
 4  -2.5    60 2000-01-01 z500  m         1     1     1         5592.
 5   0      60 2000-01-01 z500  m         1     1     1         5589.
 6   2.5    60 2000-01-01 z500  m         1     1     1         5582.
 7   5      60 2000-01-01 z500  m         1     1     1         5570.
 8   7.5    60 2000-01-01 z500  m         1     1     1         5556.
 9  10      60 2000-01-01 z500  m         1     1     1         5538.
10  12.5    60 2000-01-01 z500  m         1     1     1         5518.
```

The value to display spatially is WT computed from self organizing map to identify different spatial configurations in a panel plot.

**Comment by eliocamp** [comment]
Hi, @fipoucat, I don't think this issue is related to metR in particular. You should ask this kind of questions in some support community like StackOverflow, a community Slack, or even on mastodon with the #RStats hashtag. 

I edited your issue to add formatting. I don't fully understand the nature of these data, but it seems like something that could be plotted with `geom_rect(aes(x, y, fill = WT))`.
